### ISSUE TITLE
Many bugs with task.defense

### ISSUE THREAD

**Issue by pandabear41** [ScreepsOCS/screeps.behaviour-action-pattern#552] opened 2017-01-18 20:48 UTC
1. It ignores. SPAWN_DEFENSE_ON_ATTACK
2. The minControllerLevel = 3 is also ignored. I will get defenders spawning in RCL2.
3. The task gets confused for attackers sitting in the exit or entering and leaving room. Defender spawns, then defender recycles. 
4. The task ignores if it is in safe mode or not. (Should not spawn any defenders if safe mode is active)
5. The spawned defenders will follow creeps through exit if placed correctly. (which was how someone was bypassing my safe mode and drained all energy since defense is high queue).

**Comment by cyberblast** [comment] 2017-01-18 22:32
also #542 . Doesn't seem to work in all cases... (or at all anymore?)

**Comment by whardeman** [comment] 2017-01-19 14:11
I see invader notifications, but I'm not getting defenders at all for invaders in remote rooms. This, combined with the aggressive spawning of claimer creeps for remote mining is becoming a major energy drain if I'm not monitoring the situation constantly. Recently fed a string of probably 5 or 6 reservers to a single invader because the room was queue two, and each would die before the next one finished spawning.

**Comment by torin555** [comment] 2017-01-19 14:48
I'm having this problem too, lost about 80k energy in one room and 20k in another last night because they both kept sending creeps to their deaths until I noticed it. I came up with the idea to cloak the remote mining flag while there's an invader in the room. Then once the invader is killed, the flag could be uncloaked. Since even if the defense system was working, it would still most likely send creeps to their death in the meantime.

**Comment by dkluempers** [comment] 2017-01-20 06:53
I am seeing this also.  Reserved rooms get invaders and no defenders spawn.  Just happened after the update on 01/17/17 I think.  I am still amazed at the incredible work you guys put out !!!!!

**Comment by torin555** [comment] 2017-01-20 06:54
possibly fixed by #570

**Comment by cyberblast** [comment] 2017-01-20 12:42
> 1. It ignores. SPAWN_DEFENSE_ON_ATTACK

Confirmed. Will fix.

> 2. The minControllerLevel = 3 is also ignored. I will get defenders spawning in RCL2.

Yes, these notations in the beginning of each task were nowhere interpreted. It's possible now (with #570), but I'd prefer to select rooms by minEnergyCapacity. Which is nearly the same like RCL, but if you are advancing to the next RCL you are still not able to "spawn more". minEnergyCapacity will respect that. 

Proposed room selection criteria:
* maxRange: 4
* minEnergyCapacity: 800

> 3. The task gets confused for attackers sitting in the exit or entering and leaving room. Defender spawns, then defender recycles. 

Hmm yes, thats bad, but hard to change. 
It will not recycle if you have vision in the room the intruder is leaving to. 
But if it can't be found anymore (GetObjectById), the creep will recycle. 
We should maybe postpone that issue a bit. 
Feel free to create a separate 'change' issue to keep track of it. 

> 4. The task ignores if it is in safe mode or not. (Should not spawn any defenders if safe mode is active)

Hmm, no t sure about that one. You can still attack intruders when in safe mode. If it goes away you can recycle and get your energy back... 
Alternative would be ignoring any intruder, which is not perfect as well..

> 5. The spawned defenders will follow creeps through exit if placed correctly. (which was how someone was bypassing my safe mode and drained all energy since defense is high queue). 

Yes, that is intended behaviour (as long as that enemy creep can still be found the defender will try to kill it). 

Also, you can prevent spawning defenders in those cases by adding the room (of initial impact) to DEFENSE_BLACKLIST.

**Comment by Dasku** [comment] 2017-01-20 17:04
Seems to be working again after recent PR 👍

**Comment by whardeman** [comment] 2017-01-20 22:44
Just FYI, with the recent PR merges, I'm getting auto-defenders again when Invaders appear. 🙌

**Comment by dkluempers** [comment] 2017-01-21 17:29
I am getting  auto-defenders in main rooms. I am removing the defender flag from claimed room Green/Brown to see what happens when an invader appears.

**Comment by cyberblast** [comment] 2017-01-21 17:40
>  I am removing the defender flag 

Well, I think it's a bit confusing now. 
The defense flag (yellow/yellow) has no relation to task.defense. 
Defender creeps spawn regardless of such a flag in all of "your" rooms (owned, reserved, mining), as soon as a foreign intruder appears. 

The defense flag will spawn guards for additional strategic camps or to prepare an invasion (regardless of any intruder).

**Comment by dkluempers** [comment] 2017-01-21 17:50
Nah, I think that it is me not understanding things.  I did see an intruder in one of my reserved/claimed rooms (Green/Brown) but did not see any message for auto defenders.  But I did have a Guard there from the Yellow/Yellow flag.  I was thinking that since there was a guard there the closest room would not actually spawn the auto defenders.  I just wanted to check that.  Thanks for the help.

**Comment by cyberblast** [comment] 2017-01-21 18:42
yes, thats correct. The defense task will not spawn an auto defender when there is enough "defense" present in the room.

**Comment by cyberblast** [comment] 2017-01-21 19:26
all mentioned issues solved or spread into sub issues (#571). 
Please create new issues for new issues ;)

**Closed by cyberblast** 2017-01-21 19:26 UTC
Labels: ! Bug, # Military, / Ready
