### ISSUE TITLE
room.statistics.invaders grows rapidly with repeat hostiles

### ISSUE THREAD

**Issue by jisaf** [ScreepsOCS/screeps.behaviour-action-pattern#651] opened 2017-02-01 14:17 UTC
If a hostile creep enters and exits a room repeatedly, a new hostile invader gets logged each time.

```
        E86S19		{12}
	
	    links		[0]
	
	    hostileIds		[0]
	
	    statistics		{6}
	
	        invaders		[4668]
```

I hit the max memory in about 12 hours with 2 rooms being attacked in this way.

Perhaps this code in room.js should filter out "recently seen creeps":
```

        'hostiles': {
            configurable: true,
            get: function() {
                if( _.isUndefined(this._hostiles) ){
                    this._hostiles = this.find(FIND_HOSTILE_CREEPS, { filter : Task.reputation.hostileOwner });
                }
                return this._hostiles;
            }
        },
```

**Comment by torin555** [comment] 2017-02-01 17:20
related to #605

**Comment by chobobobo** [comment] 2017-03-05 08:44
I just cleared out about 130kb memory from one room that was all notifications about invaders because my creep had been wandering into a neighbours base.  This had severe repercussions on CPU usage (~8CPU/tick).

**Comment by Dasku** [comment] 2017-03-07 12:55
Just to add to this:
asku [12:52 PM] 
I've found an issue which is becoming a bit annoying and im sure could get worse. Currently I get an email every time my observer spots an enemy (I have 2 players near me that mine rooms on the other side of a highway, and therefore I spot creeps every 50-200 ticks.). Whilst I dont think we should remove the email option as it could spot a valid attack, maybe we need a "grey list" like a white list, but just ignores spotted creeps from that player to avoid the email spam ?

I guess the creeps spotted in highway rooms also add to the memory issue.

**Comment by OverlordQ** [comment] 2017-03-07 17:28
Essentially dupe of #605

**Closed by OverlordQ** 2017-03-07 17:28 UTC
Labels: ! Bug, / Help Wanted, High Priority
