### ISSUE TITLE
Current build has issues with workers RCL 1/2/3

### ISSUE THREAD

**Issue by pandabear41** [ScreepsOCS/screeps.behaviour-action-pattern#509] opened 2017-01-16 00:37 UTC
This happens in RCL 1/2/3 where if the number of workers is greater than the amount of available fields ( of all sources in the room, then the workers will hop back and forth and keep toggling from idle and harvesting action. I had a room with one harvest spot on each source and once when workers were all spawned they all hopped back and forth and weren't working.

I have code from around 069cd4efe26a37e67de232b4b6d4a2642feb4be5 and it is not broken, but the current dev branch has this issue.

**Comment by pandabear41** [comment] 2017-01-16 00:39
I simulated this in my current room by spawning more workers than available mining spots. See attached replay of what happens.

screeps.com/s/Ig2hRP

**Comment by cyberblast** [comment] 2017-01-20 13:22
Sorry, for late picking. 
Can anybody please check it this problem persists? A lot has been changed/fixed in the meanwhile... 
I still have to wait for 8 days until novice area will release. :/ can't claim a new room.

**Comment by Dasku** [comment] 2017-01-20 13:29
I currently have a RCL 2 and RCL 3 room, not encountered this issue.

The only thing I could say here is my RCL 3 room took a while to get to RCL 2-3 as each source only had 1 available field for mining on each. Sometimes a worker was idle  while waiting to mine, but they then mined and built/upgraded as they should.

**Comment by cyberblast** [comment] 2017-01-20 13:59
👍 as intended

**Closed by cyberblast** 2017-01-20 13:59 UTC
Labels: ! Bug, # Core
