### ISSUE TITLE
Population Collapse At Room Level 6 Does Not Recover Automatically

### ISSUE THREAD

**Issue by TafThorne** [ScreepsOCS/screeps.behaviour-action-pattern#301] opened 2016-12-15 16:34 UTC
About a week ago I had a bug in my version of the code which stopped Upgraders from spawning.  This stopped everything else from spawning to.  The end result was that I had no creeps for a few hours.  Bad times, broken roads ensued and so forth.  

The weird thing was that after I reverted my code noting spawned.  I had too little energy left in the expansions to do anything complicated.  There was only a few hundred energy in my ownly spawn.  This is the state things stayed in for quite a long time.  

I managed to manually fix this by spawning a worker unit and then a hauler unit.  I had a lot of energy in storage but nothing in my extentions.  Once a worker could do some mining and get my some energy I could make a hauler.  Once that could redistribute energy I quickly got back up and running with higher level creeps. The problem was that first bit of recovery.  

Haulers will not spawn without a miner existing. If there is a lot of energy in storage, that restriction could be relaxed.  That would allow a population recovery from total collapse if you had enough energy for a hauler.  

Workers do not seem to spawn when you are a higher level with no charged extensions.  If your room has a population of less than or equal to one I think we should always try and spawn a basic worker, no matter the level.

**Comment by pandabear41** [comment] 2016-12-15 17:23
This is a duplicate of #283 and fixed in 325f69d
If you had at least 150 energy, a hauler should of spawned.

**Comment by TafThorne** [comment] 2016-12-15 17:44
Ah, sorry about that.  I probably took my copy of the code before that was fixed.

**Closed** 2016-12-15 18:11 UTC
Labels: duplicate
