### ISSUE TITLE
remoteHaulers choosing their own destiny - escape bound!

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#863] opened 2017-02-26 22:24 UTC
![image](https://cloud.githubusercontent.com/assets/22677773/23344323/49504114-fc72-11e6-9e3c-93ccb3ed0be1.png)

Caught these 2 guys making a break for it. They wernt the first either. Both had different flags in their names but seemed to be on the same path. 100% sure no flags anywhere over there.

**Comment by karlthepagan** [comment] 2017-02-26 22:26
Are they headed to a flag named _OCS?

**Comment by Dasku** [comment] 2017-02-26 22:27
1 more hauler and a reserver in the same room

no flag-1 (reserver)

hauler below
![image](https://cloud.githubusercontent.com/assets/22677773/23344348/b0e35e10-fc72-11e6-92b2-7d6a993e3363.png)

**Comment by Dasku** [comment] 2017-02-27 11:04
![image](https://cloud.githubusercontent.com/assets/22677773/23359083/8a7bcc8e-fcdc-11e6-8b18-fbf007102349.png)

**Comment by Dasku** [comment] 2017-02-27 11:07
![image](https://cloud.githubusercontent.com/assets/22677773/23359171/e5964bf8-fcdc-11e6-938f-2c0a186aacd9.png)

**Comment by chobobobo** [comment] 2017-02-27 22:38
@Dasku when you say no flag-1 (reserver) do you mean they didn't have a flag assigned to them, or their flag had been removed?  Or the flag was valid, they just decided to run?

**Comment by chobobobo** [comment] 2017-02-27 22:57
I have added some error checking to the action.travelling code, if those errors were the cause of what you saw then you should be seeing some error messages in your log now instead of having pilgramage creeps.

**Comment by Dasku** [comment] 2017-02-27 23:25
Sorry that was the least descriptive response ever. No was in response to Karl asking if it was heading to _OCS flag. However, I later found they are going to _OCS flag even though they have genuine flag names as shown in the picture. There didn't seem to be a specific error message. I usually noticed when I got a list of invaders including workers for a player 10 rooms away.

**Comment by chobobobo** [comment] 2017-02-27 23:30
Right, by the time they were there the error message would likely have disappeared from the log..

**Comment by chobobobo** [comment] 2017-03-20 14:54
I believe this has since been resolved, if it is still happening, please reopen.

**Comment by karlthepagan** [comment] 2017-03-28 00:24
With traveler it's easy to see when this happens: `[5:21:46 PM]TRAVELER: incomplete path for remoteHauler-alphaBMine-1 from [room E6N79 pos 21,40] to [room W0N0 pos 49,49]. Route length undefined.`

W0N0 49,49 is a giveaway.

**Comment by chobobobo** [comment] 2017-03-28 04:24
Sadly, it appears this is still happening, we need to put together a PR to at least catch this when it happens and let people know.

**Comment by karlthepagan** [comment] 2017-03-28 19:57
the current issue is dropping action:
```
 Game.getObjectById('58dab223324042f26a0af5ba').action.name
 dropping
 Game.getObjectById('58dab223324042f26a0af5ba').target
 [flag _OCS]
```

**Comment by karlthepagan** [comment] 2017-03-28 22:10
another find

```
 Game.getObjectById('58dadbbcc44d23ed344d3751').action.name
 dropping
 Game.getObjectById('58dadbbcc44d23ed344d3751').target
 [flag Flag1]
```

I also have no idea how this guy happened to target Flag1

**Comment by karlthepagan** [comment] 2017-03-28 22:13
After setting him to idle the Flag1 target and dropping action are back.

**Closed by karlthepagan** 2017-03-28 22:13 UTC
Labels: ! Bug, High Priority
